apiVersion: v1
kind: Namespace
metadata:
  name: pcp-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pcp-ksa # The KSA used for Workload Identity
  namespace: pcp-prod
  annotations:
    iam.gke.io/gcp-service-account: pcp-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pcp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: pcp-prod
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
# MCP Orchestrator Deployment (Upgraded for Workload Identity & Secrets CSI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-orchestrator
  namespace: pcp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-orchestrator
  template:
    metadata:
      labels:
        app: mcp-orchestrator
    spec:
      serviceAccountName: pcp-ksa
      containers:
      - name: orchestrator
        image: gcr.io/your-project-id/mcp-orchestrator:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: pcp-secrets-volume
          mountPath: "/mnt/secrets"
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: pcp-secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "pcp-gcp-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-orchestrator-service
  namespace: pcp-prod
spec:
  selector:
    app: mcp-orchestrator
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
# Command Poller Deployment (Upgraded for HA, Workload Identity & Secrets CSI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-poller
  namespace: pcp-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: command-poller
  template:
    metadata:
      labels:
        app: command-poller
    spec:
      serviceAccountName: pcp-ksa
      containers:
      - name: poller
        image: gcr.io/your-project-id/command-poller:latest
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MCP_BASE_URL
          value: "http://mcp-orchestrator-service:8080"
        volumeMounts:
        - name: pcp-secrets-volume
          mountPath: "/mnt/secrets"
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pcp-secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "pcp-gcp-secrets"
---
# SecretProviderClass to link GCP Secret Manager to the CSI Driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pcp-gcp-secrets
  namespace: pcp-prod
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/notion-token/versions/latest"
        fileName: "NOTION_TOKEN"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/mcp-private-key/versions/latest"
        fileName: "MCP_PRIVATE_KEY"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/groq-api-key/versions/latest"
        fileName: "GROQ_API_KEY"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/mistral-api-key/versions/latest"
        fileName: "MISTRAL_API_KEY"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/google-doc-id/versions/latest"
        fileName: "GOOGLE_DOC_ID"