name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  # Replace with your GCP Project ID
  GCP_PROJECT_ID: your-gcp-project-id
  GKE_CLUSTER: pcp-cluster
  GKE_REGION: us-central1
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        # Replace with your WIF provider details
        workload_identity_provider: 'projects/YOUR_GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/YOUR_POOL_ID/providers/YOUR_PROVIDER_ID'
        # Replace with a dedicated SA for CI/CD
        service_account: 'your-cicd-service-account@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}

    - name: Build and Push MCP Orchestrator Image
      run: |-
        docker build -t ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/mcp-orchestrator:${{ github.sha }} -f server/mcp-orchestrator.Dockerfile .
        docker push ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/mcp-orchestrator:${{ github.sha }}

    - name: Build and Push Command Poller Image
      run: |-
        docker build -t ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/command-poller:${{ github.sha }} -f server/command_poller/command_poller.Dockerfile .
        docker push ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/command-poller:${{ github.sha }}

    - name: Deploy to GKE
      run: |-
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}

        # Update deployment images with the new SHA tag
        kubectl set image deployment/mcp-orchestrator orchestrator=${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/mcp-orchestrator:${{ github.sha }} -n pcp-prod
        kubectl set image deployment/command-poller poller=${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/pcp/command-poller:${{ github.sha }} -n pcp-prod
